---
title: "Mutual Information Networks of the H3N2 Polymerase"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(associationsubgraphs)
```

<br/>
<br/>

Network visualizations generated using the [associationubgraphs](https://github.com/nstrayer/associationsubgraphs) package by Nick Strayer.

---


# H3N2 Polymerase

```{r echo = FALSE, message = FALSE, warning = FALSE}
mi_iav_info2 <- readRDS("/Users/saraharcos/Desktop/Lauring Lab/MI_Networks_App/data/mi_iav_info2.rds")
mip_noHA<- readRDS("/Users/saraharcos/Desktop/Lauring Lab/timeMI/data/h3n2_meaned_mip_noHA.rds")
mi_noHA_small <- mip_noHA %>%
  select(V1, V2, mi) %>%
  left_join(mi_iav_info2, by = c("V1" = "index")) %>%
  left_join(mi_iav_info2, by = c("V2" = "index")) %>%
  select(a = "id.x", b = "id.y", strength = mi) %>%
  filter(strength > 0) %>%
  slice_max(order_by = strength, n = 1800)

sub_structure_noHA <- mi_noHA_small %>%
  calculate_subgraph_structure()

visualize_subgraph_structure(
  association_pairs = mi_noHA_small,
  node_info = mi_iav_info2 %>% select(-index),
  subgraph_results = sub_structure_noHA,
  trim_subgraph_results = FALSE,
  default_step = as.integer(37)
)
```


<br/>
<br/>

---

<br/>
<br/>

# H3N2 Polymerase with HA

```{r echo = FALSE, message = FALSE, warning = FALSE}
mi <- readRDS("/Users/saraharcos/Desktop/Lauring Lab/timeMI/data/h3n2_meaned_mi.rds") %>%
  select(V1, V2, mi) %>%
  left_join(mi_iav_info2, by = c("V1" = "index")) %>%
  left_join(mi_iav_info2, by = c("V2" = "index")) %>%
  select(a = "id.x", b = "id.y", strength = mi) %>%
  filter(strength > 0)

mi_small <- mi %>%
  slice_max(order_by = strength, n = 2000)

sub_structure <- mi_small %>%
  calculate_subgraph_structure()

visualize_subgraph_structure(
  association_pairs = mi_small,
  node_info = mi_iav_info2 %>% select(-index),
  subgraph_results = sub_structure,
  trim_subgraph_results = FALSE,
  default_step = as.integer(114)
)
```
